name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Данный процесс будет запускаться при каждом пуше в ветку main
  pull_request:
    branches:
      - master  # Также при пулл-запросах в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu для выполнения задач

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Checkout code
      uses: actions/checkout@v2  # Это клонирует ваш репозиторий

    # Шаг 2: Настройка Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'  # Укажите версию Python, которую используете

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Установите зависимости из вашего файла requirements.txt

    # Шаг 4: Запуск тестов
    - name: Run tests
      run: |
        pytest  # Запуск тестов с помощью pytest или другого тестового фреймворка
